### ISSUE TITLE
vl_kdforest_build() does not seem to build a tree

### ISSUE THREAD

**Issue by sromberg** [vlfeat/vlfeat#100]
vl_kdforest_build() does not seem to build a tree: I am not sure if I am doing something wrong here or I discovered a bug. 

I am trying to build a kd-tree (one only) for 3D points. I followed the API and a few examples I found. However, it seems that the tree is not really built as vl_kdforest_get_depth_of_tree(forest, 0) reports a tree depth of 0, which basically indicates that "no tree was built at all".

This is the code I use:
    
    vector< IdxPt_<DIMS, T> >& pts = ... custom point type ...
    const size_t numPoints = pts.size();

    vl_size dimensions = DIMS;
    vl_size numTrees   = 1;

    T* dataPts = new T[numPoints*DIMS];
    for(size_t i=0; i<numPoints; i++){
        for(size_t k=0; k<DIMS; k++)
            dataPts[i*DIMS+k] = pts[i].data[k];
    }

    VlKDForest* forest = vl_kdforest_new(VL_TYPE_FLOAT, dimensions, numTrees, VlDistanceL2);
    vl_kdforest_build(forest, numPoints, dataPts);

    cout << "DIMS:                              " << DIMS << endl;
    cout << "numPoints:                         " << numPoints << endl;
    cout << "vl_kdforest_get_data_dimension:    " << vl_kdforest_get_data_dimension(forest) << endl;
    cout << "vl_kdforest_get_num_trees:         " << vl_kdforest_get_num_trees(forest) << endl;
    cout << "vl_kdforest_get_depth_of_tree:     " << vl_kdforest_get_depth_of_tree(forest, 0) << endl;
    cout << "vl_kdforest_get_num_nodes_of_tree: " << vl_kdforest_get_num_nodes_of_tree(forest, 0) << endl;

    if( forest )
        vl_kdforest_delete(forest);
    if( dataPts )
        delete[] dataPts;

And the output I get is as follows:

    DIMS:                              3
    numPoints:                         1000000
    vl_kdforest_get_data_dimension:    3
    vl_kdforest_get_num_trees:         1
    vl_kdforest_get_depth_of_tree:     0
    vl_kdforest_get_num_nodes_of_tree: 1

Why is the depth of the three 0? I suspect I am using the API in the wrong manner although I tried to follow the docs. What is wrong here?

**Comment by vedaldi** [comment]
This is likely a problem with the data. E.g. if all data is identical then the tree has just one leaf node. For instance, in MATLAB:

```matlab
run toolbox/vl_setup.m ;

x = zeros(3,10000) ; % all identical, trees collapse
forest = vl_kdtreebuild(x,'verbose') ;

x = randn(3,10000) ; % fine
forest = vl_kdtreebuild(x,'verbose') ;
```

demonstrates what happens in the two cases:

```
vl_kdforestbuild: data double [3 x 10000]
vl_kdforestbuild: threshold selection method: median
vl_kdforestbuild: number of trees: 1
vl_kdforestbuild: tree 0: depth 0, num nodes 1

vl_kdforestbuild: data double [3 x 10000]
vl_kdforestbuild: threshold selection method: median
vl_kdforestbuild: number of trees: 1
vl_kdforestbuild: tree 0: depth 14, num nodes 19999
```
