### ISSUE TITLE
Mex files for Win 64, version 0.9.20

### ISSUE THREAD

**Issue by micw523** [vlfeat/vlfeat#127]
Hi:
When I tried to setup vlfeat on my machine (Win 10/Matlab 2016a), it popped up the following message:

Invalid MEX-file 'C:\Users***\Documents\MATLAB\vlfeat-0.9.20\toolbox\mex\mexw64\vl_version.mexw64':
The specified module could not be found.

The same problem happened to a few other mex modules as well when I ran the demo/test.

I downloaded v0.9.19 and it is running fine. I am thinking the mex files contained in version 0.9.20 might be broken.
Thanks, XW

**Comment by macsnair** [comment]
Hi,
When I am trying to compile vlfeat (0.9.20 or 0.9.19, either cases) on my machine (Win 10/Matlab 2016a), using the command 'vl_compile', I am getting the following error:
Error using mex
vl_fisher.c
C:\Programs Files ( x86)\\Windows Kits\10\\include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005:
'snprintf': macro redefinition

[directory_path]'\vlfeat-0.9.19-bin\vlfeat-0.9.19\vl\host.h(315): note: see previous
definition of 'snprintf'

C:\Program Files (x86)\Windows Kits\10\\include\10.0.10150.0\ucrt\stdio.h(1927): fatal error
C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration

Error in vl_compile (line 140)
    mex(cmd{:}) ;

Any help will be much appreciated.

Thanks,
Manu

**Comment by shawndfernandes** [comment]
http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definition
