### ISSUE TITLE
VS 2015 Compatibility change

### ISSUE THREAD

**Issue by shawndfernandes** [vlfeat/vlfeat#146]
Dear All,

To ensure VlFeat 0.9.20 gets compiled MS VC++ VS 2015, make following changes to host.h in line 315 & line 335 under /vl/ directory.

//#  define snprintf _snprintf //commented for VS 2015 compatibility

http://www.vlfeat.org/download/vlfeat-0.9.20-bin.tar.gz

http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti

**Comment by AiWei123** [comment]
hello，I use matlab2016a and vs2015 to compile  VlFeat 0.9.20 ,vl setup can work and vl compile also compile successfully.but when I run vl_version verbose,there is a error occurring:Invalid MEX-file 'D:\MATLAB\R2016a\toolbox\slic\vlfeatroot\toolbox\mex\mexw64\vl_version.mexw64':,I find many ways to solve it,but it cant't work.can you give some advice?thank you very much.

**Comment by shawndfernandes** [comment]
Dear AiWei123,

I am able to compile VlFeat 0.9.20

MEX C:\Users\~\Desktop\vlfeat-0.9.20\toolbox\slic\vl_slic.c
Building with 'Microsoft Visual C++ 2015 Professional (C)'.
MEX completed successfully.

Output of vl_demo also works

vl_slic: image = [128 x 128 x 3]
vl_slic: regionSize = 10
vl_slic: regularizer = 0.01
vl_slic: minRegionSize = 2
vl_slic: image = [128 x 128 x 3]
vl_slic: regionSize = 10
vl_slic: regularizer = 0.1
vl_slic: minRegionSize = 2
vl_slic: image = [128 x 128 x 3]
vl_slic: regionSize = 10
vl_slic: regularizer = 1
vl_slic: minRegionSize = 2
vl_slic: image = [128 x 128 x 3]
vl_slic: regionSize = 30
vl_slic: regularizer = 0.01
vl_slic: minRegionSize = 25
vl_slic: image = [128 x 128 x 3]
vl_slic: regionSize = 30
vl_slic: regularizer = 0.1
vl_slic: minRegionSize = 25
vl_slic: image = [128 x 128 x 3]
vl_slic: regionSize = 30
vl_slic: regularizer = 1
vl_slic: minRegionSize = 25

Please find below link for output of vl_demo with SLIC for VLFeat

http://www.vlfeat.org/overview/slic.html

**Comment by shawndfernandes** [comment]
Closed by commit:

https://github.com/vlfeat/vlfeat/commit/d31a87598272b383366f2358e65c16af00f88daf
