### ISSUE TITLE
"Invalid MEX-file" and "Missing dependent shared libraries", Matlab 2017a, MacOS 10.12

### ISSUE THREAD

**Issue by thelittlekid** [vlfeat/vlfeat#151]
I got the error below after I upgrade Matlab from 2016b to 2017a: 
Invalid MEX-file
```
'.../MATLAB/vlfeat/vlfeat-0.9.20/toolbox/mex/mexmaci64/vl_version.mexmaci64':
Missing dependent shared libraries:
'@loader_path/libvl.dylib' required by
'.../MATLAB/vlfeat/vlfeat-0.9.20/toolbox/mex/mexmaci64/vl_version.mexmaci64'
```

Plus a bunch of missing symbols like: 
```
Missing symbol '___tolower' required by
'.../MATLAB/vlfeat/vlfeat-0.9.20/toolbox/mex/mexmaci64/vl_version.mexmaci64'
```
I did not make any change on vlfeat folder, and 'libvl.dylib' is right under the '/toolbox/mex/mexmaci64/' folder. 

Is someone able to run vlfeat with Matlab 2017a on MacOS?

**Comment by ChengliangTang** [comment]
I met the same problem. Actually, I reinstalled the MATLAB and get the above results when I run vlfeat. However, I don't know how to solve it.

**Comment by philippesalembier** [comment]
I also had the same problem. This can be solved by recompiling the library following the instruction described in http://www.vlfeat.org/compiling-unix.html. I used: 
make MEX=/Applications/MATLAB_R2017a.app/bin/mex ARCH=maci64

Hope this helps

**Comment by thelittlekid** [comment]
Thanks, it works.

**Comment by zzzyq** [comment]
Hi, I face the same problem. I type "make MEX=/Applications/MATLAB_R2017a.app/bin/mex ARCH=maci64" in terminal but it shows "make: *** No targets specified and no makefile found.  Stop." Did I miss any steps?

**Comment by thelittlekid** [comment]
Did you change your working directory to VLFEATROOT according to http://www.vlfeat.org/compiling-unix.html? There should be a makefile in that directory. It worked for me.

**Comment by zzzyq** [comment]
Thanks for your quick reply. Yeah, I tried but there is still something wrong. I downgraded my MATLAB to 2016b finally. It became normal.

**Comment by craigchamplin** [comment]
It worked for me.  Did you make sure to compile Matlab support?

**Comment by hkjpkg** [comment]
I face the same problem.  It's really hard to use MATLAB 2017a in iOS 10.12.5.
I try to use "make MEX=/Applications/MATLAB_R2017a.app/bin/mex ARCH=maci64" in terminal,
however it does not work. 

> Invalid MEX-file '/Users/*****/Documents/MATLAB/VLFEATROOT/toolbox/mex/mexmaci64/vl_version.mexmaci64': Missing dependent
> shared libraries:
> '@loader_path/libvl.dylib' required by
> '/Users/*****/Documents/MATLAB/VLFEATROOT/toolbox/mex/mexmaci64/vl_version.mexmaci64'

**Comment by sunwell1994** [comment]
@zzzyq same as you. it does not work. I am not sure what happened.

**Comment by NCH18** [comment]
Sorry to revive an old thread but I am stuck on this. I am using Mac OS 10.13.6 and Matlab 2015a. I followed instructions on this website:
[http://www.vlfeat.org/compiling-unix.html](http://www.vlfeat.org/compiling-unix.html)
When I try
> sudo make CC=BREWROOT/opt/llvm/bin/clang DISABLE_OPENMP=no

I get 

> /bin/bash: /usr/local/bin/brew/opt/llvm/bin/clang: Not a directory
> Detected compiler: clang
> MATLAB support disabled
> The MALTAB version will be detected in the next phase of Make
>              CC bin/maci64/libvl.dylib
> /bin/bash: /usr/local/bin/brew/opt/llvm/bin/clang: Not a directory
> make: *** [bin/maci64/libvl.dylib] Error 126

So I tried to follow instructions here about clang:
[https://www.ics.uci.edu/~majumder/VC/211HW3/vlfeat/doc/compiling-unix.html](https://www.ics.uci.edu/~majumder/VC/211HW3/vlfeat/doc/compiling-unix.html)

But when I try

> sudo port install apple-gcc42 

I get

> --->  Computing dependencies for apple-gcc42
> --->  Fetching distfiles for apple-gcc42
> Error: apple-gcc42 is not supported on OS X versions newer than El Capitan.
> Error: Failed to fetch apple-gcc42: unsupported platform
> Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_lang_apple-gcc42/apple-gcc42/main.log for details.
> Error: Follow https://guide.macports.org/#project.tickets to report a bug.
> Error: Processing of port apple-gcc42 failed

Any advice much appreciated!
