### ISSUE TITLE
Results different between x86 and AVX implementation?

### ISSUE THREAD

**Issue by nh2** [vlfeat/vlfeat#161]
Hi,

we're seeing different results / features detected in `v0.9.20` depending on whether we set `STD_CFLAGS` to `x86-64` or `broadwell`.

We're using covdet feature detection + sift featue descriptors.

Is it expected that the AVX and non-AVX implementations give different results?

Thanks!

**Comment by bitonic** [comment]
we're actually not sure now if we were using the sse2 versions of the avx versions.

more worryingly, we are getting _better_ results with avx/sse2, although that might be a red herring

**Comment by bitonic** [comment]
actually, it seems like AVX is a red herring -- the difference between x86-64 and broadwell is there even disabling AVX/SSE2 and even OpenMP explicitly

**Comment by nh2** [comment]
With `gcc (GCC) 5.4.0`, results are different between `x86-64` and `haswell`.

With `clang 3.9` they are not.

**Comment by bitonic** [comment]
it turns out the results were different because of gcc's liberal use of fused multiple and add. on clang fma is turned off by default.

**Comment by nh2** [comment]
We have figured out now what the problem is.

Architectures `>= haswell` have [FMA (fused multiply-add)](https://en.wikipedia.org/wiki/FMA_instruction_set#FMA3_instruction_set) instructions that do combined floating point multiplication and addition with higher precision.

That's why floating point results can differ.

GCC turns it on by default if the `-march` is given, [clang doesn't](http://lists.llvm.org/pipermail/cfe-dev/2015-September/045110.html).
