### ISSUE TITLE
sift from command line out of memory

### ISSUE THREAD

**Issue by JasonDoingGreat** [vlfeat/vlfeat#183]
I am using sift from command line on mac and got the following error message:

```
sift(490,0x7fff89999380) malloc: *** mach_vm_map(size=4342377827252789248) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
sift(490,0x7fff89999380) malloc: *** mach_vm_map(size=17369511309011156992) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
sift: err: Could not allocate enough memory. (2)
```

The code I am working on is (Python):
```
params="--edge-thresh 10 --peak-thresh 5"

if imagename[-3:] != 'pgm':
  # create a pgm file
  im = Image.open(imagename).convert('L')
  im.save('tmp.pgm')
  imagename = 'tmp.pgm'

cmmd = str("sift " + imagename + " --output=" + resultname + " " + params)
os.system(cmmd)
```
Image using is of size: 1280 × 1000, 333 KB.

Anyone has idea about how to solve this problem? 
Thanks.

**Comment by xfangfang** [comment]
I got the same problem, did you solve it? Thanks

**Comment by ngunhaSO** [comment]
Are you guys working on Mac by using the book 'Programming compute vision with python'? 
I am having an issue installing the sift with Mac

**Comment by p3sp12** [comment]
I confronted same problem when I was working on 'Programming compute vision with python".
Using the oldest version of vlfeat worked well on my Macbook2017 and Windows10 PC.
32bit/64bit ver doesn't seem a problem. I hope it solves a problem you have.

**Comment by b-mandelbrot** [comment]
Just change the param `--output=` to `--output` and everything will work fine.

**Comment by sujayk96** [comment]
Changing the output parameter is not working for me. I am working on mac. Does the system architecture have to do anything with this?
