### ISSUE TITLE
error while loading shared libraries: libvl.so

### ISSUE THREAD

**Issue by zyzhong** [vlfeat/vlfeat#37]
I try to use g++ to compile the simplest "Hello World" program of vlfeat. My system is Ubuntu 12.04 LTS 64-bit.

I can compile successfully, but when I run it, it failed with message like this:
"error while loading shared libraries: libvl.so: cannot open shared object file: No such file or directory"

Anyone tell me how to fix it?

**Comment by hhxjzyr** [comment]
Please tell me how to set that , thanks

**Comment by apoorvamalemath** [comment]
Open vlfeat/toolbox/mex/octave/mexa64 
and open octave from that location
