### ISSUE TITLE
vl_imsmooth problem

### ISSUE THREAD

**Issue by n-patricia** [vlfeat/vlfeat#39]
Hi,

I got this error when I compute vl_phow

"Attempt to execute SCRIPT vl_imsmooth as a function"

Someone gave this solution:
You are getting this error because your path ".../vlfeat-0.9.16/toolbox/imop/vl_imsmooth.m"
has a higher precedence than " ...../vlfeat-0.9.16/toolbox/mex/mexa64/vl_imsmooth.mexa64"
so you can simply run

> > pathtool 

I tried it, but it doesn't work. Thanks
# 

novi

**Comment by XueDx** [comment]
Try run these 2 lines together rather than only line 1.  xxx is my vlfeat dir.
```
addpath(genpath([xxx,'vlfeat\\toolbox']));
addpath(genpath([xxx,'vlfeat\\toolbox\\mex']));
```
