### ISSUE TITLE
Issue with running vl_sift.m

### ISSUE THREAD

**Issue by mtmarsh2** [vlfeat/vlfeat#52]
When I go through the tutorial on vl_sift on the site, I get the error: "Attempt to execute SCRIPT vl_sift as a function". Is this a common installation error or something?

**Comment by soham1255** [comment]
When I go through the tutorial on vl_sift on the site, I get the error: "Attempt to execute SCRIPT vl_sift as a function". Is this a common installation error or something?
all file are on its location
